//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.08.07 at 06:25:10 PM MSK
//

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}sourceDbUrl"/>
 *         &lt;element ref="{}sourceDbUser"/>
 *         &lt;element ref="{}sourceDbPassword"/>
 *         &lt;element ref="{}sourceDbScheme"/>
 *         &lt;element ref="{}targetDbUrl"/>
 *         &lt;element ref="{}targetDbUser"/>
 *         &lt;element ref="{}targetDbPassword"/>
 *         &lt;element ref="{}targetDbScheme"/>
 *         &lt;element ref="{}threadCount"/>
 *         &lt;element ref="{}autoCommit"/>
 *         &lt;element ref="{}rowsPerTran"/>
 *         &lt;element ref="{}queries"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                                 "sourceDbUrl",
                                 "sourceDbUser",
                                 "sourceDbPassword",
                                 "sourceDbScheme",
                                 "targetDbUrl",
                                 "targetDbUser",
                                 "targetDbPassword",
                                 "targetDbScheme",
                                 "threadCount",
                                 "autoCommit",
                                 "rowsPerTran",
                                 "queries"
})
@XmlRootElement(name = "dbBlobExtractorParams")
@SuppressWarnings("javadoc")
public class DbBlobExtractorParams {

    @XmlElement(required = true)
    protected String sourceDbUrl;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sourceDbUser;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sourceDbPassword;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sourceDbScheme;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetDbUrl;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String targetDbUser;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String targetDbPassword;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String targetDbScheme;
    @XmlElement(required = true)
    protected BigInteger threadCount;
    protected boolean autoCommit;
    @XmlElement(required = true)
    protected BigInteger rowsPerTran;
    @XmlElement(required = true)
    protected Queries queries;

    /**
     * Gets the value of the sourceDbUrl property.
     * @return
     * possible object is {@link String }
     */
    public String getSourceDbUrl() {
        return sourceDbUrl;
    }

    /**
     * Sets the value of the sourceDbUrl property.
     * @param value
     * allowed object is {@link String }
     */
    public void setSourceDbUrl(String value) {
        sourceDbUrl = value;
    }

    /**
     * Gets the value of the sourceDbUser property.
     * @return
     * possible object is {@link String }
     */
    public String getSourceDbUser() {
        return sourceDbUser;
    }

    /**
     * Sets the value of the sourceDbUser property.
     * @param value
     * allowed object is {@link String }
     */
    public void setSourceDbUser(String value) {
        sourceDbUser = value;
    }

    /**
     * Gets the value of the sourceDbPassword property.
     * @return
     * possible object is {@link String }
     */
    public String getSourceDbPassword() {
        return sourceDbPassword;
    }

    /**
     * Sets the value of the sourceDbPassword property.
     * @param value
     * allowed object is {@link String }
     */
    public void setSourceDbPassword(String value) {
        sourceDbPassword = value;
    }

    /**
     * Gets the value of the sourceDbScheme property.
     * @return
     * possible object is {@link String }
     */
    public String getSourceDbScheme() {
        return sourceDbScheme;
    }

    /**
     * Sets the value of the sourceDbScheme property.
     * @param value
     * allowed object is {@link String }
     */
    public void setSourceDbScheme(String value) {
        sourceDbScheme = value;
    }

    /**
     * Gets the value of the targetDbUrl property.
     * @return
     * possible object is {@link String }
     */
    public String getTargetDbUrl() {
        return targetDbUrl;
    }

    /**
     * Sets the value of the targetDbUrl property.
     * @param value
     * allowed object is {@link String }
     */
    public void setTargetDbUrl(String value) {
        targetDbUrl = value;
    }

    /**
     * Gets the value of the targetDbUser property.
     * @return
     * possible object is {@link String }
     */
    public String getTargetDbUser() {
        return targetDbUser;
    }

    /**
     * Sets the value of the targetDbUser property.
     * @param value
     * allowed object is {@link String }
     */
    public void setTargetDbUser(String value) {
        targetDbUser = value;
    }

    /**
     * Gets the value of the targetDbPassword property.
     * @return
     * possible object is {@link String }
     */
    public String getTargetDbPassword() {
        return targetDbPassword;
    }

    /**
     * Sets the value of the targetDbPassword property.
     * @param value
     * allowed object is {@link String }
     */
    public void setTargetDbPassword(String value) {
        targetDbPassword = value;
    }

    /**
     * Gets the value of the targetDbScheme property.
     * @return
     * possible object is {@link String }
     */
    public String getTargetDbScheme() {
        return targetDbScheme;
    }

    /**
     * Sets the value of the targetDbScheme property.
     * @param value
     * allowed object is {@link String }
     */
    public void setTargetDbScheme(String value) {
        targetDbScheme = value;
    }

    /**
     * Gets the value of the threadCount property.
     * @return
     * possible object is {@link BigInteger }
     */
    public BigInteger getThreadCount() {
        return threadCount;
    }

    /**
     * Sets the value of the threadCount property.
     * @param value
     * allowed object is {@link BigInteger }
     */
    public void setThreadCount(BigInteger value) {
        threadCount = value;
    }

    /**
     * Gets the value of the autoCommit property.
     */
    public boolean isAutoCommit() {
        return autoCommit;
    }

    /**
     * Sets the value of the autoCommit property.
     */
    public void setAutoCommit(boolean value) {
        autoCommit = value;
    }

    /**
     * Gets the value of the rowsPerTran property.
     * @return
     * possible object is {@link BigInteger }
     */
    public BigInteger getRowsPerTran() {
        return rowsPerTran;
    }

    /**
     * Sets the value of the rowsPerTran property.
     * @param value
     * allowed object is {@link BigInteger }
     */
    public void setRowsPerTran(BigInteger value) {
        rowsPerTran = value;
    }

    /**
     * Gets the value of the queries property.
     * @return
     * possible object is {@link Queries }
     */
    public Queries getQueries() {
        return queries;
    }

    /**
     * Sets the value of the queries property.
     * @param value
     * allowed object is {@link Queries }
     */
    public void setQueries(Queries value) {
        queries = value;
    }

}
